export const ADD_ALARM = "ADD_ALARM"
export const DELETE_ALARM = "DELETE_ALARM"
export const ACTIVATED_ALARM = "ACTIVATED_ALARM"
export const CHECKED_ALARM = "CHECKED_ALARM"
export const ALL_CHECKED_ALARM = "ALL_CHECKED_ALARM"
export const EDIT_ALARM = "EDIT_ALARM"
export const CHANGE_DELETE_MODE = "CHANGE_DELETE_MODE"
export const REMAINING_TIME = "REMAINING_TIME"


